/**
 * M5: the frozen bytes both SDK ports read, so neither proves only that it agrees with itself.
 *
 * These vectors are not part of the specification (§5.1 leaves provisioning to the deployment); they
 * pin what this project's two ports agree on. See `interop/README.md`.
 *
 * The file was generated by the Python port. That makes this suite the cross-implementation check:
 * it reads bytes this port never wrote.
 */

import { readFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';
import { type Jwk, jwkThumbprint, publicJwk, publicKeyOf } from '../src/l2/jwk';
import { KeyRegistry, type KeyRole, loadToolKey, SignatureAlgorithm } from '../src/l2/keys';

const HERE = dirname(fileURLToPath(import.meta.url));
const vectors = JSON.parse(readFileSync(resolve(HERE, '..', 'interop', 'key-exchange.json'), 'utf8')) as {
  tool_jwks: { keys: Jwk[] };
  host_jwks: { keys: Jwk[] };
  thumbprints: Record<string, string>;
  private_keys: { kid: string; pkcs8_base64: string; pkcs8_pem: string; public_jwk_thumbprint: string }[];
  refused_jwks: { name: string; because: string; jwk: Jwk }[];
  refused_jwks_sets: { name: string; because: string; jwks: unknown }[];
  refused_thumbprints: { name: string; jwk: Jwk }[];
  role_mismatch: { load_into_role: string; jwks: { keys: Jwk[] } };
};

describe('the committed interop vectors (§5.1, RFC 7517)', () => {
  it.each([
    ['tool', vectors.tool_jwks],
    ['host', vectors.host_jwks],
  ] as const)('a committed %s set loads and renders back identically', (role, document) => {
    const registry = new KeyRegistry(role as KeyRole);
    registry.loadJwks(document);
    expect(registry.toJwks()).toEqual(document);
  });

  it('every committed thumbprint matches', () => {
    // A person comparing a key out of band sees the same value from either port (RFC 7638).
    for (const jwk of [...vectors.tool_jwks.keys, ...vectors.host_jwks.keys]) {
      expect(jwkThumbprint(jwk)).toBe(vectors.thumbprints[String(jwk.kid)]);
    }
  });

  it('a committed private key reads back to its published public half', () => {
    // The PKCS#8 one port writes is the PKCS#8 the other reads (M2).
    for (const entry of vectors.private_keys) {
      const key = loadToolKey(entry.kid, new Uint8Array(Buffer.from(entry.pkcs8_base64, 'base64')));
      const rendered = publicJwk(key.keyId, key.publicKey, SignatureAlgorithm.ED25519, 'tool');
      expect(jwkThumbprint(rendered)).toBe(entry.public_jwk_thumbprint);
    }
  });

  it.each(
    vectors.refused_jwks.map((c) => [c.name, c.jwk] as const),
  )('a committed refusal is refused (%s)', (_name, jwk) => {
    // The set each port refuses has to be the same set, or one accepts what the other will not.
    expect(() => publicKeyOf(jwk)).toThrow();
  });

  it('a set of the other role is refused', () => {
    // A tool key held as a host's lets a tool sign itself into the countersigned state (§5.2).
    const registry = new KeyRegistry(vectors.role_mismatch.load_into_role as KeyRole);
    expect(() => registry.loadJwks(vectors.role_mismatch.jwks)).toThrow();
  });

  it.each(
    vectors.refused_jwks_sets.map((c) => [c.name, c.jwks] as const),
  )('a committed set refusal leaves the registry untouched (%s)', (_name, jwks) => {
    // A refused set lands nothing: a half-provisioned registry verifies some records and rejects others.
    const registry = new KeyRegistry('tool');
    const before = registry.toJwks();
    expect(() => registry.loadJwks(jwks as never)).toThrow();
    expect(registry.toJwks()).toEqual(before);
  });

  it.each(
    vectors.refused_thumbprints.map((c) => [c.name, c.jwk] as const),
  )('a thumbprint of an incomplete key is refused (%s)', (_name, jwk) => {
    // A thumbprint of something that is not a key would match nothing a person could check (RFC 7638).
    expect(() => jwkThumbprint(jwk)).toThrow();
  });

  it('a committed private key reads the same from PEM', () => {
    // A secret manager hands a key over as PEM; both ports read it to the same key as the DER.
    for (const entry of vectors.private_keys) {
      const fromDer = loadToolKey(entry.kid, new Uint8Array(Buffer.from(entry.pkcs8_base64, 'base64')));
      const fromPem = loadToolKey(entry.kid, new TextEncoder().encode(entry.pkcs8_pem));
      expect([...fromPem.publicKey]).toEqual([...fromDer.publicKey]);
    }
  });
});
